### ISSUE TITLE
suggestion: just two commands

### ISSUE THREAD

**Issue by gurgeous** [sgryjp/vscode-stable-sort#1]
This extension is great, exactly what I need! Suggestion - can we reduce it to just two commands?

1. words vs line (the extension can guess this, right?)
1. remove char-code (I've never wanted this in my years of sorting)
1. switch to numeric (if all the elements start with a number)

Then it would just be:

Stable Sort Ascending
Stable Sort Descending

or maybe even override the default commands if that's possible. Thanks for creating such a great extension!

**Comment by sgryjp** [comment]
Thank you for feedback!

Yes, I agree with you on that this extension should provide "smart" commands... choosing a proper command from those many choices is cumbersome.

Currently I think the extension's behavior should be like next:

- It sorts words if:
  1. there is only one selection range, and
  2. it's inside a line (does not contain EOL)
- Otherwise it sorts lines

If you feel something wrong about this, please let me know. Perhap I missed something.

**Comment by gurgeous** [comment]
Looks right to me, thanks!

The multiple selections case is interesting. Seems like a bit of an edge case. Maybe it isn't that important.

**Comment by sgryjp** [comment]
Hi @gurgeous,

I just released v1.0.0, which provides the unified commands. I believe you can receive update inside VSCode. I hope you enjoy this new extension :)

(Note that the shortcut was changed to <kbd>Ctrl+Alt+R</kbd> since now it does not sort **L**ines only, nor **W**ords only anymore. Except that, there should not be a noticeable changes.)

**Comment by gurgeous** [comment]
Great! I think there might a bug or two? I tried this:

before
![image](https://user-images.githubusercontent.com/526195/59567855-06483d80-9028-11e9-9c21-1cda578596aa.png)

after
![image](https://user-images.githubusercontent.com/526195/59567857-0d6f4b80-9028-11e9-9f2b-4677bf7f2616.png)

expected (using standard vscode sort)
![image](https://user-images.githubusercontent.com/526195/59567869-27109300-9028-11e9-89cf-f1d71dd19740.png)

**Comment by sgryjp** [comment]
Hi @gurgeous,

Hmm yes there must be a bug... Thank you for reporting!

BTW it seems that you executed word sorting (in descending order.) Can you expand selection range one character ahead and try again? Doing so sorts the selected lines and it should work fine.

One question: If you were asked to select some lines, will you make selection range as in your report (using mouse, perhaps)? I tend to start selection from the beginning of the first line to the beginning of the one line ahead of the final line to be selected. But if this is inconvenient for you, I consider to add an option.

**Comment by gurgeous** [comment]
Ah! I see - if I add a trailing newline and select that too it works properly. I typically select lines just by hitting shift-up or shift-down a few times. I don't use my mouse for this. The builtin sort doesn't mind. I often sort with a selection that looks like this:

before
![image](https://user-images.githubusercontent.com/526195/59571517-6ce64f00-905a-11e9-8fce-52d75c70058d.png)

after
![image](https://user-images.githubusercontent.com/526195/59571521-81c2e280-905a-11e9-94df-290324f6a85c.png)

A suggestion for how it might work:

1) Are there any newlines in the selection? If so, sort by line. First expand the selection to include any lines touched by the selection. 
2) If no newlines, sort by word.

Would that work for all the common use cases?

**Comment by sgryjp** [comment]
Hi @gurgeous,

Thank you for suggestion again! I created an alpha version which basically do as your suggested. If you could spare some time, please try it ([how to install from a `.vsix` is described here](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix)):

https://github.com/sgryjp/vscode-stable-sort/raw/feat-prefer-word-sorting/vscode-stable-sort-20190622.vsix

Since I personally like the feature to sort words spread over multiple lines, I added a setting `stableSort.preferWordSorting` which brings back the behavior of v1.0.0; words will be sorted if selection starts or ends in a middle of a line. I believe this option makes both of us happy.

**Comment by gurgeous** [comment]
I tried it out and it seems to work perfectly! My use case (just select some lines by hitting shift-down a few times) is working now. I didn't try any edge cases, though. Thanks for updating, this is great!

**Comment by sgryjp** [comment]
Great! Now everything is fine so I'll release the alpha as v1.1. Thank you for contributing @gurgeous!
