### ISSUE TITLE
Adding dot separator

### ISSUE THREAD

**Issue by AlainPilon** [sgryjp/vscode-stable-sort#20]
Hi. Could you add the "." (dot) to the list of separators. 

Thanks

**Comment by sgryjp** [comment]
Hi. Could you show me how you plan to use this feature?

I’m concerned that simply adding `.` as a separator might be difficult because Smart Sort supports sorting CSV fields that often contain numbers with decimal points (e.g., 3.14). If you could tell me more about your use case, I could consider a more flexible approach.

**Comment by AlainPilon** [comment]
This requirement comes from wanting to sort css classes when using haml markup. 

Ex:

```
.text-center.pt-12
  %h1.mb-4.text-4xl.tracking-tight.font-bold.text-gray-900.dark:text-white
    = @user.name
```

In the sample above, I would like to be able to sort `.mb-4.text-4xl.tracking-tight.font-bold.text-gray-900.dark:text-white` as sorting classes is a Tailwind best practice. 

Also note that it is possible in haml to not define the html tag (instead it will use a div by default), ex:

```
.mb-4.font-medium
  = @user.last_name
```

**Comment by sgryjp** [comment]
@AlainPilon Thank you for clarification! Now I understand your request.

I think trying to use dot as a separator **only if no whitespace characters are selected** is acceptable. Do you think this behavior is acceptable?

### Background of the design

For example, let's think the example illustrated below:

    .modal .warning.button, .modal .button.danger { ... }
    \___________________________________________/
      |    \_____________/  \___________________/
      |      |                |
      |      +-- Range B      +-- Range A
      +-- RANGE C

Current Smart Sort (1.2.1) will choose separator as next: comma for range C, space for range A and B. After adding the dot as separator as described above, Smart Sort will choose separator as: comma for range C, space for B, and dot for A.

**Comment by AlainPilon** [comment]
> I think trying to use dot as a separator only if no whitespace characters are selected is acceptable. Do you think this behaviour is acceptable?

Totally.

Another option, to protect other users from unexpected sort, would be to have the dot separator sorting as an option (false by default).

**Comment by sgryjp** [comment]
@AlainPilon Hi, I just released version 1.3.0 which includes the feature.

I decided to make the feature on by default (can opt-out too) because it should no be a surprise change as previous version of Smart Sort did nothing under the condition to execute the new feature.

Please try it and if you notice anything, please let me know. Thank you!

**Comment by AlainPilon** [comment]
Cool! I am working on everything but front end code these days. But as soon as I am, I will test it right away! Thx!

**Comment by AlainPilon** [comment]
Just to circle back on this after working with it for a few days: so far everything works perfectly. Thx.
